language: go
go:
  - 1.14
script: go build -o ./bin/solana_exporter github.com/certusone/solana_exporter/cmd/solana_exporter
deploy:
  provider: s3
  access_key_id: "$S3_ACCESS_KEY"
  secret_access_key: "$S3_SECRET_KEY"
  region: "us-west-2"
  bucket: "travis.hub"
  upload-dir: solana_exporter
  local_dir: ./bin
