#language: go
#go:
#  - 1.14
#deploy:
#  provider: s3
#  access_key_id: "$S3_ACCESS_KEY"
#  secret_access_key: "$S3_SECRET_KEY"
#  region: "us-west-2"
#  bucket: "travis.hub"

language: ruby

services:
- docker
  
before_install:
- docker run -t --rm -w /opt -v ${PWD}:/opt golang:1.14 go build -o /opt/bin/solana_exporter github.com/certusone/solana_exporter/cmd/solana_exporte

deploy:
  provider: s3
  access_key_id: "$S3_ACCESS_KEY"
  secret_access_key: "$S3_SECRET_KEY"
  region: "us-west-2"
  bucket: "travis.hub"
  upload-dir: atomlab/solana_exporter/bin
